name: Build Pyxis Template Service Image

on:
  push:
    branches: [ "main" ]

permissions: write-all

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Update Version Number for Models
      uses: jacobtomlinson/gha-find-replace@2.0.0
      with:
        find: "<Version>1.0.0</Version>"
        replace: "<Version>1.0.${{ github.run_number }}</Version>"
        include: "**TemplateService.csproj"
    - name: Log in to Docker Hub
      uses: docker/login-action@v2.1.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Extract container metadata from hub
      id: meta
      uses: docker/metadata-action@v4.1.1
      with:
        images: pyxisint/Templateservice
    - name: Build the Docker image
      uses: docker/build-push-action@v3.2.0
      with:
        context: .
        push: true
        tags: pyxisint/Templateservice:1.0.${{ github.run_number }}
        labels: ${{ steps.meta.outputs.labels }}
